VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.create_args =  ["--privileged"]
    d.ports =  ["80:8080"]
  end

  config.ssh.username = "root"
  config.ssh.private_key_path = "phusion.key"
  config.vm.provision "shell", inline: "service tomcat7 start"

end
